version: '3.8'

services:
  api:
    build: .
    container_name: posts-manager-api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/posts-manager
      - FRONTEND_URL=http://localhost:4200
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: posts-manager-db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
